### ISSUE TITLE
Could the scripts for the calculation of mselectivity, SNR, and cselectivity for [xcms, mzmine] 's format's output file be shared?

### ISSUE THREAD

**Issue by YUANMENG-1** [shuzhao-li-lab/asari#78]
1.You have compared asari with xcms, mzmine, msdial in upstream processing, but do you have tools like IPO, autotuner, and SLAW for upstream parameter optimization? After parameter optimization, have you also compared mselectivity, SNR, and cselectivity? Additionally, you mentioned SLAW, which is a tool that includes both parameter optimization and upstream processing. Have you compared it with asari?

2. I would like to ask if you have separate scripts for calculating mselectivity, SNR, and cselectivity for xcms, mzmine, and msdial. Can you share these scripts? I am working with hundreds or thousands of samples of untargeted metabolomics data using IPO + xcms, SLAW, and IPO + default parameters. I have run over a hundred samples with these three workflows, but I cannot determine which one is most likely to produce accurate results. If I want to use your three evaluation metrics, can I borrow your scripts for that purpose?

**Comment by YUANMENG-1** [comment]
Sorry, Add a question
3. I would like to inquire about the absence of the secondary structure format MGF in the output files of ASARI. Typically, both XCMS and the SLAW workflow generate comprehensive files, each containing both MSI and MSII data. I also want to inquire if the annotation results here are based on the of MSII spectrums, or if only MSI data ?

**Comment by jmmitc06** [comment]
Hi YuanMeng-1, 

Shuzhao may be able to provide more detail; but, I can address some of the questions posed here. 

1. Currently there are no tools for auto-optimizing the parameters of asari; however, the only parameter we have found that need to be altered are the mass resolution of the instrument and occasionally the minimum peak intensity and its related params. The latter of which, the autoheight function that already exists in asari appears to do a good job. I personally have not compared SLAW with asari. 

2. I don't have those scripts on me right now (at a conference) but when I get back I will ask.

3. Outputting MGF or other MS2 data formats is something I intend to implement in the future but there is currently another solution that is in the prototype stage that will achieve the same result. We have a pipeline that wraps asari that can also generate MS2 level annotations but instead of outputting the MGF files explicitly, I'm rescanning the mzML files at annotation time to extract the MS2 data and annotate. The annotations generated by the main asari package are MS1 only but are generated using our khipu package that first collects sets of features suspected to belong to the same compound and annotates them as a unit.

**Comment by jmmitc06** [comment]
Were you able to get the information you needed? If not or you continue to have problems, please re-open this issue.
